version: "3.9"

services:
  back:
    container_name: sertanejofy_back
    build:
      context: ./sertanejofy-back/
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    volumes:
      - ./sertanejofy-back/:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5434:5434
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  front:
    container_name: front
    build:
      context: ./sertanejofy-front/
    ports:
      - 3000:3000
    depends_on:
      - back
    command: sh -c "npm run dev"
    volumes:
      - ./sertanejofy-front/:/app
